const PHONE="5518997553071";const CONSENT_KEY="bdm_measurement_consent";const ATTRIBUTION_KEY="bdm_attribution";
function clean(v,l=120){return String(v||"").slice(0,l).replace(/[<>]/g,"").trim()}
function id(prefix){return window.crypto&&typeof window.crypto.randomUUID==="function"?window.crypto.randomUUID():prefix+"_"+Date.now()}
function pushEvent(payload){window.dataLayer=window.dataLayer||[];window.dataLayer.push(payload);let consent="denied";try{consent=localStorage.getItem(CONSENT_KEY)||"denied"}catch{}if(consent!=="granted")return;if(typeof window.gtag==="function")window.gtag("event",payload.event,payload);if(typeof window.fbq==="function"){payload.event==="generate_lead"?window.fbq("track","Lead",payload):window.fbq("trackCustom",payload.event,payload)}}
function attribution(){const p=new URLSearchParams(location.search),keys=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","gbraid","wbraid","fbclid"];let stored={};try{stored=JSON.parse(sessionStorage.getItem(ATTRIBUTION_KEY)||"{}")}catch{}const a={};for(const k of keys)a[k]=clean(p.get(k)||stored[k]||"");a.landing_path=clean(stored.landing_path||location.pathname,160);try{a.referrer_host=clean(stored.referrer_host||(document.referrer?new URL(document.referrer).hostname:"direct"),100)}catch{a.referrer_host="direct"}try{sessionStorage.setItem(ATTRIBUTION_KEY,JSON.stringify(a))}catch{}document.querySelectorAll('a[href="#qualificacao"]').forEach(link=>link.addEventListener("click",()=>{const section=link.closest("section")?.id||(link.closest("header")?"header":"footer");pushEvent({event:"bdm_partner_cta_click",event_id:id("cta"),conversion_destination:"whatsapp",cta_id:link.dataset.ctaId||section+"_cta",section,label:link.textContent.trim(),...a})}))}
function readAttribution(){try{return JSON.parse(sessionStorage.getItem(ATTRIBUTION_KEY)||"{}")}catch{return{}}}
function consent(){const box=document.querySelector("#consent-banner");if(!box)return;let current=null;try{current=localStorage.getItem(CONSENT_KEY)}catch{current="denied"}if(!current)box.hidden=false;box.querySelectorAll("[data-consent]").forEach(btn=>btn.addEventListener("click",()=>{const value=btn.dataset.consent==="granted"?"granted":"denied";try{localStorage.setItem(CONSENT_KEY,value)}catch{}box.hidden=true;window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:"consent_update",analytics_storage:value,ad_storage:value})}))}
function faq(){document.querySelectorAll(".faq-list details").forEach((item,i)=>item.addEventListener("toggle",()=>{if(item.open)pushEvent({event:"bdm_faq_open",event_id:id("faq"),faq_index:i+1,faq_question:item.querySelector("summary")?.textContent.trim()||""})}))}
function finalView(){const section=document.querySelector(".qualification");if(!section||!("IntersectionObserver"in window))return;const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;pushEvent({event:"bdm_final_cta_view",event_id:id("view")});observer.disconnect()},{threshold:.35});observer.observe(section)}
function form(){const f=document.querySelector("#partner-form"),error=document.querySelector("#form-error");if(!f||!error)return;f.querySelectorAll("input,select").forEach(field=>{const clear=()=>field.setAttribute("aria-invalid","false");field.addEventListener("input",clear);field.addEventListener("change",clear)});f.addEventListener("submit",e=>{e.preventDefault();const required=[...f.querySelectorAll("[required]")],invalid=required.filter(field=>!field.checkValidity());required.forEach(field=>field.setAttribute("aria-invalid",invalid.includes(field)?"true":"false"));if(invalid.length){error.textContent="Preencha os campos obrigatórios e aceite o consentimento para continuar.";invalid[0].focus();return}const data=new FormData(f),lead={name:clean(data.get("name"),100),phone:clean(data.get("phone"),20),region:clean(data.get("region"),100),role:clean(data.get("automotive_role"),100),capital:clean(data.get("capital"),100)},a=readAttribution();pushEvent({event:"generate_lead",event_id:id("lead"),lead_type:"authorized_representative",automotive_role:lead.role,capital_status:lead.capital,region:lead.region,...a});const origin=[a.utm_source,a.utm_medium,a.utm_campaign].filter(Boolean).join(" / "),message=["Olá, BDM. Preenchi a análise para representante autorizado.","","Nome: "+lead.name,"WhatsApp: "+lead.phone,"Cidade/região: "+lead.region,"Atuação automotiva: "+lead.role,"Capital disponível: "+lead.capital,origin?"Origem: "+origin:"","","Quero saber se minha região está disponível."].filter(Boolean).join("\n");error.textContent="";location.assign("https://wa.me/"+PHONE+"?text="+encodeURIComponent(message))})}
document.documentElement.classList.add("js-ready");attribution();consent();faq();finalView();form();const year=document.querySelector("#year");if(year)year.textContent=String(new Date().getFullYear());